openapi: 3.0.3
info:
  title: Product API
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /products:
    get:
      parameters:
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/q"
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
              examples:
                multiple:
                  value:
                    - name: Tampico
                      expiration_datetime: 2025-09-01T12:54:00
                      price: 2500.00
                    - name: Socolait
                      expiration_datetime: 2025-12-25T18:12:00
                      price: 1500.00
                empty:
                  value: []

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
      example:
        name: Doritos
        expiration_datetime: 2026-08-30T10:23:00
        price: 2000.00

  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
      example: 1
    q:
      name: q
      in: query
      required: false
      schema:
        type: string
      example: Doritos
